Fix type errors (#203)
The follwoing type error is raised when we execite `npm run typecheck`
command.

```console
$ npm run typecheck

> openarm-site@0.0.0 typecheck
> tsc

src/components/BoMTable.tsx:73:37 - error TS2345: Argument of type 'T[]' is not assignable to parameter of type '{ unitPrice: number; quantity: number; }[]'.
  Type 'T' is not assignable to type '{ unitPrice: number; quantity: number; }'.
    Type 'Record<string, any>' is missing the following properties from type '{ unitPrice: number; quantity: number; }': unitPrice, quantity

73   const totalCost = formatTotalCost(components);
                                       ~~~~~~~~~~
```

We added the BoMRecord type to define the necessary attributes for
BoMTable.